# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: jump.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='jump.proto',
  package='jump',
  syntax='proto3',
  serialized_options=b'Z)github.com/acidonper/jump-app-protos/jump',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\njump.proto\x12\x04jump\"8\n\x07JumpReq\x12\r\n\x05\x63ount\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\r\n\x05jumps\x18\x03 \x03(\t\")\n\x08Response\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t26\n\x0bJumpService\x12\'\n\x04Jump\x12\r.jump.JumpReq\x1a\x0e.jump.Response\"\x00\x42+Z)github.com/acidonper/jump-app-protos/jumpb\x06proto3'
)




_JUMPREQ = _descriptor.Descriptor(
  name='JumpReq',
  full_name='jump.JumpReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='count', full_name='jump.JumpReq.count', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='jump.JumpReq.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='jumps', full_name='jump.JumpReq.jumps', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=76,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='jump.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='jump.Response.code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='jump.Response.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=78,
  serialized_end=119,
)

DESCRIPTOR.message_types_by_name['JumpReq'] = _JUMPREQ
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

JumpReq = _reflection.GeneratedProtocolMessageType('JumpReq', (_message.Message,), {
  'DESCRIPTOR' : _JUMPREQ,
  '__module__' : 'jump_pb2'
  # @@protoc_insertion_point(class_scope:jump.JumpReq)
  })
_sym_db.RegisterMessage(JumpReq)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'jump_pb2'
  # @@protoc_insertion_point(class_scope:jump.Response)
  })
_sym_db.RegisterMessage(Response)


DESCRIPTOR._options = None

_JUMPSERVICE = _descriptor.ServiceDescriptor(
  name='JumpService',
  full_name='jump.JumpService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=121,
  serialized_end=175,
  methods=[
  _descriptor.MethodDescriptor(
    name='Jump',
    full_name='jump.JumpService.Jump',
    index=0,
    containing_service=None,
    input_type=_JUMPREQ,
    output_type=_RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_JUMPSERVICE)

DESCRIPTOR.services_by_name['JumpService'] = _JUMPSERVICE

# @@protoc_insertion_point(module_scope)
